# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

build:
    stage: build
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist/

lint:
    stage: test
    script:
        - npm install
        - npm run lint

publish:
    stage: deploy
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm publish
    dependencies:
        - build
    only:
        - /^v.*$/
    except:
        - branches
